# Important: Use "flutter packages get", not "pub get".
name: flutter_built_redux
author: David Marne <davemarne@gmail.com>
version: 1.0.0
description: Built_redux provider for Flutter
homepage: https://github.com/davidmarne/flutter_built_redux

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_redux: ^8.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter
