# Important: Use "flutter packages get", not "pub get".
name: flutter_built_redux
author: David Marne <davemarne@gmail.com>
version: 3.0.0
description: Built_redux provider for Flutter
homepage: https://github.com/davidmarne/flutter_built_redux
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux.git
      ref: v9.x

  flutter:
    sdk: flutter

  meta: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.4
  built_value: ^8.0.6
  built_value_generator: ^8.0.6
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: 1.7.0 # 1.7.1 has a bug: analyzer-1.7.1/lib/src/error/best_practices_verifier.dart:1998:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null
  meta: ^1.4.0
  test_api: ^0.4.0
