# Important: Use "flutter packages get", not "pub get".
name: flutter_built_redux
author: David Marne <davemarne@gmail.com>
version: 0.6.1
description: Built_redux provider for Flutter
homepage: https://github.com/davidmarne/flutter_built_redux
dependencies:
  flutter:
    sdk: flutter
    
  meta:
  
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux

dev_dependencies:
  build_runner: '1.10.6'
  built_value: 
  built_value_generator: 
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: '0.40.6'
      
environment:
  sdk: ">=2.9.0 <3.0.0"
  
