# Important: Use "flutter packages get", not "pub get".
name: flutter_built_redux
author: David Marne <davemarne@gmail.com>
version: 0.6.1
description: Built_redux provider for Flutter
homepage: https://github.com/davidmarne/flutter_built_redux
dependencies:
  flutter:
    sdk: flutter
    
  meta:
  
  built_value: ^7.1.0
  
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  

dependency_overrides:
  analyzer: 0.40.6
      
environment:
  sdk: ">=2.9.0 <3.0.0"
  
